---
- name: Check if GitLab configuration file already exists.
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file

- name: Check if GitLab is already installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check if GitLab Yum Repo exists
  stat: path=/etc/yum.repos.d/gitlab_gitlab-ce.repo
  register: gitlab_repo_exists

- name: debug information
  ansible.builtin.debug:
    var: gitlab_repo_exists
    verbosity: 1

- name: debug information
  ansible.builtin.debug:
    var: ansible_facts.packages
    verbosity: 1

- meta: end_play

# Based on https://about.gitlab.com/install/#centos-7
- name: Install GitLab dependencies.
  package:
    name:
      - curl
      - openssh-server
      - perl
      - python3-policycoreutils
      - policycoreutils
      - git
    state: present

- name: Enable http(s) ports
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - "http"
    - "https"

- name: Download GitLab repository installation script.
  get_url:
    url: "https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh"
    dest: /tmp/gitlab_install_repository.sh
    validate_certs: true
  when: not gitlab_file.stat.exists

- name: Install GitLab repository.
  command: bash /tmp/gitlab_install_repository.sh
  register: output
  when: not gitlab_repo_exists.stat.exists

- name: Update GitLab Yum repo to target RHEL 7 since RHEL 8/9 isn't supported
  ansible.builtin.replace:
    path: /etc/yum.repos.d/gitlab_gitlab-ce.repo
    regexp: 'el\/9'
    replace: 'el/8'
    backup: no
  when: not gitlab_repo_exists.stat.exists

- name: Install GitLab
  package:
    name: "gitlab-ce-{{ gitlab_version }}"
    state: present
  when: "gitlab_version not in ansible_facts.packages['gitlab-ce'].version"


# Start and configure GitLab. Sometimes the first run fails, but after that,
# restarts fix problems, so ignore failures on this run.
- name: Reconfigure GitLab (first run).
  command: >
    gitlab-ctl reconfigure
    creates=/var/opt/gitlab/bootstrapped
  failed_when: false

- name: Copy GitLab configuration file.
  template:
    src: "gitlab.rb.j2"
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart gitlab