---
- name: Set variables
  set_fact:
    mariadb_name: mariadb
    wordpress_network: wordpress_net

- name: Create wordpress group
  group:
    name: wordpress
    state: present

- name: Create wordpress user
  user:
    name: wordpress
    password: '!'
    group: wordpress
    shell: /sbin/nologin
    create_home: no
    append: yes
    comment: "Wordpress nologin User"
    state: present

- name: Create directories
  file:
    path: "/opt/{{ item }}"
    state: directory
    owner: wordpress
    group: "0"
    recurse: yes
    mode: g+rwx
  with_items:
    - mysql
    - mysql-backup
    - nginx/config
    - nginx/certs
    - nginx/logs

- name: Create a wordpress network
  become: true
  containers.podman.podman_network:
    name: "{{ wordpress_network }}"

- name: Create a mariadb container
  containers.podman.podman_container:
    name: "{{ mariadb_name }}"
    image: docker.io/mariadb:latest
    restart_policy: always
    network_mode: "{{ wordpress_network }}"
    ports:
      - 3306:3306/tcp
      - 33060:33060/tcp
    env:
      MYSQL_ROOT_PASSWORD: "{{ mariadb_root_password }}"
      MYSQL_DATABASE: "{{ mariadb_database_name }}"
      MYSQL_USER: "{{ mariadb_user }}"
      MYSQL_PASSWORD: "{{ mariadb_password }}"
    volumes: "/opt/mysql:/var/lib/mysql"

- name: Create a container to backup mariadb
  containers.podman.podman_container:
    name: "mysql-backup"
    image: docker.io/databack/mysql-backup:latest
    restart_policy: always
    network_mode: "{{ wordpress_network }}"
    env:
      DB_SERVER: "{{ mariadb_name }}"
      DB_PORT: 3306
      DB_USER: "{{ mariadb_user }}"
      DB_PASS: "{{ mariadb_password }}"
      DB_DUMP_TARGET: /db
    volumes: "/opt/mysql-backup:/db"

- name: Create a wordpress container
  containers.podman.podman_container:
    name: wordpress
    image: docker.io/wordpress:latest
    restart_policy: always
    network_mode: "{{ wordpress_network }}"
    ports:
      - 127.0.0.1:8080:80/tcp
    env:
      WORDPRESS_DB_HOST: "{{ mariadb_name }}"
      WORDPRESS_DB_NAME: "{{ mariadb_database_name }}"
      WORDPRESS_DB_USER: "{{ mariadb_user }}"
      WORDPRESS_DB_PASSWORD: "{{ mariadb_password }}"

- name: Copy nginx conf to remote
  template:
    src: default.conf.j2
    dest: "/opt/nginx/config/default.conf"
    group: '0'

- name: Create the nginx container
  containers.podman.podman_container:
    name: nginx
    image: docker.io/nginx:latest
    restart_policy: always
    network_mode: "{{ wordpress_network }}"
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - "/opt/nginx/config/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/opt/nginx/logs:/var/logs/nginx"
      - "/opt/nginx/certs/{{inventory_hostname}}.pem:/etc/pki/tls/certs/{{inventory_hostname}}.pem:ro"
      - "/opt/nginx/certs/{{inventory_hostname}}.key:/etc/pki/tls/private/{{inventory_hostname}}.key:ro"

- name: Enable http(s) ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - "443/tcp"
    - "80/tcp"