---
- name: Populate service facts
  service_facts:

- name: Enable EPEL repository
  become: yes
  package:
    name: epel-release
    state: present

- name: Ensure all packages are up to date
  become: yes
  ansible.builtin.package:
    name: '*'
    state: latest

- name: Install basic packages
  become: yes
  package:
    name:
      - cockpit
      - cockpit-podman
      - tmux
      - podman
      - htop
    state: present

- name: Enable cockpit
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - cockpit.service
  when:
    - "ansible_facts.services[item]['status'] != 'enabled' or ansible_facts.services[item]['state'] != 'started'"
