---
- name: Enable EPEL repository
  become: yes
  package:
    name: epel-release
    state: present

- name: Ensure all packages are up to date
  become: yes
  ansible.builtin.package:
    name: '*'
    state: latest

- name: Install basic packages
  become: yes
  package:
    name:
      - cockpit
      - cockpit-podman
      - tmux
      - podman
    state: present

- name: Enable cockpit and podman
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - podman
    - cockpit